name: Genarate audio
on: 
  push:
    branches:
      - feature/**
 
jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    strategy:
      matrix:
        node_version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install packages
      run: npm install

    - name: Run start
      run: npm run start

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: out dir
        # path: |
        # dir
        path: |
          helloworld.txt
        retention-days: 2
